version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1
  
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo Hello, 
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo World!      
  inv_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo $CIRCLE_USERNAME
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello World!" > /tmp/o1.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - o1.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: /tmp/o1.txt
      - run: cat /tmp/o1.txt

workflows:
  print_hello_world:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - inv_name
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
