version: 2.1

jobs:
  printhello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: "echo Hello, "
  printworld:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: "echo World!"  
        
workflows:
  print-hello-workflow:
    jobs:
      - printhello
      - printworld
          requires: printhello
